// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5aA6kKdkFRQtzwRyBzxVnzzqHHvFy0eQ',
    appId: '1:214001185570:web:400b3295c86bda2a022b7b',
    messagingSenderId: '214001185570',
    projectId: 'crisissync-ai-de28b',
    authDomain: 'crisissync-ai-de28b.firebaseapp.com',
    storageBucket: 'crisissync-ai-de28b.firebasestorage.app',
    measurementId: 'G-2R05JFTRKE',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2yUYU-LZtDV9UXFz2utwWjLsd9n1sXj0',
    appId: '1:214001185570:ios:24fcfaf6db8b0be0022b7b',
    messagingSenderId: '214001185570',
    projectId: 'crisissync-ai-de28b',
    storageBucket: 'crisissync-ai-de28b.firebasestorage.app',
    iosBundleId: 'com.example.crisisSyncApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2yUYU-LZtDV9UXFz2utwWjLsd9n1sXj0',
    appId: '1:214001185570:ios:24fcfaf6db8b0be0022b7b',
    messagingSenderId: '214001185570',
    projectId: 'crisissync-ai-de28b',
    storageBucket: 'crisissync-ai-de28b.firebasestorage.app',
    iosBundleId: 'com.example.crisisSyncApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5aA6kKdkFRQtzwRyBzxVnzzqHHvFy0eQ',
    appId: '1:214001185570:web:fa17c977a6bb7bdd022b7b',
    messagingSenderId: '214001185570',
    projectId: 'crisissync-ai-de28b',
    authDomain: 'crisissync-ai-de28b.firebaseapp.com',
    storageBucket: 'crisissync-ai-de28b.firebasestorage.app',
    measurementId: 'G-YHWNYPNLQK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMOI1qni3Vw6UbQlY9ZgaEra9O8ewHnaw',
    appId: '1:214001185570:android:331a52e684c7598b022b7b',
    messagingSenderId: '214001185570',
    projectId: 'crisissync-ai-de28b',
    storageBucket: 'crisissync-ai-de28b.firebasestorage.app',
  );

}